version: 0.2

phases:
  install:
    runtime-versions:
      docker: 20
      nodejs: 16
  pre_build:
    commands:
      - echo installing Dependencies
      - npm i
      - $(aws ecr get-login --no-include0email --region $AWS_DEFAULT_REGION)
  build:
    commands:
      - echo  testing
      - npm run test
      - docker build -t $IMAGE_REPO_NAME:$IMAGE_TAG
      - docker tag  $IMAGE_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing the docker image
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG
      - printf  '[{"name": "%s", "imageUrl": "%s"}]' $CONTAINER_NAME $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/$IMAGE_REPO_NAME:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json